Subscribe by tags - issue #143
eclipse-volttron/volttron-core pull request #179
Opened 2023-07-20 21:17 UTC by schandrika

Added subscribe and publish by tags feature to pubsub subsystem. Issue #143

2023-07-26 15:49 UTC, shwethanidd requested changes

2023-07-27 21:13 UTC, schandrika commented on src/volttron/client/vip/agent/subsystems/pubsub.py
> +        :type publish_multiple: boolean
Updated publish_multiple to max_publish_count parameter

2023-08-09 21:51 UTC, schandrika commented
Updates to be done based on review discussion: - 
1. move topic_source as the last parameter in publish/subscribe by tags method
2. Remove the parameter 'peer' (its always 'pubsub') and parameter 'bus' (always used with default value) from publish and subscribe methods
3. Move 'persistent_queue' parameter as part of kwargs as this is applicable only for rmq and not zmq

2023-08-10 18:36 UTC, schandrika commented
Completed 1, 3, and 4 above. Will create a new PR for point number 2 above as that will involve updating and testing all agent code and tests

2023-08-10 18:47 UTC, craig8 requested changes

2023-08-10 18:47 UTC, craig8 commented on src/volttron/client/vip/agent/subsystems/pubsub.py
> +        print("refreshing tags")
remove the print make it a log if you must.

2023-08-10 18:51 UTC, craig8 approved these changes

2023-08-11 17:00 UTC, merged